//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Puzzles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Puzzles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Puzzles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Puzzles.Puzzles", typeof(Puzzles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;grilleJeu&quot;&gt;
        ///    &lt;div id=&quot;c_0&quot; class=&quot;c&quot; l=&quot;1&quot; c=&quot;1&quot; r=&quot;1&quot; v=&quot;7&quot;&gt;
        ///        &lt;p&gt;7&lt;/p&gt;
        ///    &lt;/div&gt;
        ///    &lt;div id=&quot;c_1&quot; class=&quot;c fixe&quot; l=&quot;1&quot; c=&quot;2&quot; r=&quot;1&quot; v=&quot;9&quot;&gt;
        ///        &lt;p&gt;9&lt;/p&gt;
        ///    &lt;/div&gt;
        ///    &lt;div id=&quot;c_2&quot; class=&quot;c fixe&quot; l=&quot;1&quot; c=&quot;3&quot; r=&quot;1&quot; v=&quot;C&quot;&gt;
        ///        &lt;p&gt;C&lt;/p&gt;
        ///    &lt;/div&gt;
        ///    &lt;div id=&quot;c_3&quot; class=&quot;c&quot; l=&quot;1&quot; c=&quot;4&quot; r=&quot;1&quot; v=&quot;8&quot;&gt;
        ///        &lt;p&gt;8&lt;/p&gt;
        ///    &lt;/div&gt;
        ///    &lt;div id=&quot;c_4&quot; class=&quot;c fixe&quot; l=&quot;1&quot; c=&quot;5&quot; r=&quot;2&quot; v=&quot;E&quot;&gt;
        ///        &lt;p&gt;E&lt;/p&gt;
        ///    &lt;/div&gt;
        ///    &lt;div id=&quot;c_5&quot; class=&quot;c fixe&quot; l=&quot;1&quot; c=&quot;6&quot; r=&quot;2&quot; v=&quot;6 [rest of strin....
        /// </summary>
        public static string Sudoku_16_unsolved_nr1 {
            get {
                return ResourceManager.GetString("Sudoku_16_unsolved_nr1", resourceCulture);
            }
        }
    }
}
